import os
from dotenv import load_dotenv

load_dotenv()

ASSEMBLYAI_API_KEY = os.getenv("ASSEMBLYAI_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY")

USER_NAME = os.getenv("USER_NAME", "the user")

AUDIO_SAMPLE_RATE = 16000
AUDIO_CHANNELS = 1
AUDIO_CHUNK_SIZE = 1024
AUDIO_FORMAT = "int16"

VAD_AGGRESSIVENESS = 2
VAD_FRAME_DURATION_MS = 20

ASSEMBLYAI_LANGUAGE = "en_us"

OPENAI_MODEL = "gpt-4o"
OPENAI_TEMPERATURE = 0.7

ELEVENLABS_VOICE_ID = os.getenv("ELEVENLABS_VOICE_ID", "21m00Tcm4TlvDq8ikWAM")
ELEVENLABS_MODEL_ID = "eleven_turbo_v2"

RECONNECT_MAX_RETRIES = 3
RECONNECT_BASE_DELAY = 1

SILENCE_TIMEOUT_SECONDS = 30

